import { Subject, EbbinghausRevisionItem, AchievementBadge, CommunityPost, UserPreferences } from "../types";
import { getTodayString, addDays, generateSmartStudySchedule } from "./scheduler";

const today = getTodayString();
const yesterday = addDays(today, -1);
const target1 = addDays(today, 25);
const target2 = addDays(today, 18);

export const defaultPreferences: UserPreferences = {
  preferredStudyTime: "18:30",
  topicsPerDay: 2,
  subjectsPerDay: 2,
  notificationsEnabled: true,
  notificationPermission: "default",
};

export const initialSubjects: Subject[] = [
  {
    id: "sub-1",
    name: "Data Structures & Algorithms",
    description: "Core algorithmic patterns, complexity analysis, and problem-solving fundamentals.",
    targetDate: target1,
    color: "from-blue-600 to-indigo-600",
    icon: "code",
    resourceNames: ["Algorithms_Syllabus.pdf", "MIT_6006_LectureNotes.txt"],
    webLinks: ["https://visualgo.net", "https://leetcode.com/explore"],
    createdAt: yesterday,
    topics: [
      {
        id: "top-1-1",
        subjectId: "sub-1",
        unitNumber: 1,
        unitTitle: "Unit 1: Foundations & Algorithmic Complexity",
        topicCode: "1.1",
        title: "Big-O & Upper Bound Asymptotics",
        moduleName: "Unit 1: Foundations & Algorithmic Complexity",
        description: "Analyze algorithmic efficiency, worst-case upper bounds, and logarithmic vs polynomial scales.",
        subtopics: ["Asymptotic notation (O, Omega, Theta)", "Worst vs average case bounds", "Logarithmic scales in divide-and-conquer"],
        keyConcepts: ["Asymptotic notation", "Worst vs Average case", "Logarithmic curves"],
        difficulty: "Easy",
        estimatedMinutes: 18,
        order: 1,
        status: "completed",
        quizScore: 100,
        completedAt: yesterday,
        notes: "Remember: O(log n) implies binary division (e.g. binary search). O(n log n) is typical for optimal comparison sorts.",
      },
      {
        id: "top-1-2",
        subjectId: "sub-1",
        unitNumber: 1,
        unitTitle: "Unit 1: Foundations & Algorithmic Complexity",
        topicCode: "1.2",
        title: "Array Contiguous Memory & Index Arithmetic",
        moduleName: "Unit 1: Foundations & Algorithmic Complexity",
        description: "Contiguous RAM layout, O(1) index addressing, cache line locality, and sequential scans.",
        subtopics: ["Memory byte addressing", "O(1) index calculation formula", "CPU cache locality advantages"],
        keyConcepts: ["Contiguous memory", "O(1) direct address", "Cache locality"],
        difficulty: "Easy",
        estimatedMinutes: 15,
        order: 2,
        status: "studying",
        notes: "Arrays provide instantaneous O(1) random access because the memory address is simply base_address + index * element_size.",
      },
      {
        id: "top-1-3",
        subjectId: "sub-1",
        unitNumber: 1,
        unitTitle: "Unit 1: Foundations & Algorithmic Complexity",
        topicCode: "1.3",
        title: "Dynamic Array Resizing & Amortized Doubling",
        moduleName: "Unit 1: Foundations & Algorithmic Complexity",
        description: "Geometric capacity growth, copy cost distribution, and aggregate amortized O(1) proof.",
        subtopics: ["Capacity vs size distinction", "Doubling copy sequence 1 + 2 + 4 + ...", "Amortized O(1) mathematical proof"],
        keyConcepts: ["Capacity doubling", "Amortized analysis", "Geometric series sum"],
        difficulty: "Medium",
        estimatedMinutes: 18,
        order: 3,
        status: "not_started",
      },
      {
        id: "top-1-4",
        subjectId: "sub-1",
        unitNumber: 2,
        unitTitle: "Unit 2: Linear & Pointer Data Structures",
        topicCode: "2.1",
        title: "Singly Linked List Traversal & Pointer Operations",
        moduleName: "Unit 2: Linear & Pointer Data Structures",
        description: "Dynamic heap memory nodes, pointer dereferencing, sequential iteration, and pointer rewiring.",
        subtopics: ["Node struct pointer layout", "O(1) prepend vs O(N) append", "Pointer rewiring order"],
        keyConcepts: ["Pointer dereferencing", "O(1) head insertion", "Null terminator"],
        difficulty: "Medium",
        estimatedMinutes: 18,
        order: 4,
        status: "not_started",
      },
      {
        id: "top-1-5",
        subjectId: "sub-1",
        unitNumber: 2,
        unitTitle: "Unit 2: Linear & Pointer Data Structures",
        topicCode: "2.2",
        title: "Sentinel Dummy Nodes & Edge Case Elimination",
        moduleName: "Unit 2: Linear & Pointer Data Structures",
        description: "Eliminating null-pointer branch checks during list insertions and head deletions with sentinel nodes.",
        subtopics: ["Dummy head pattern", "Uniform deletion loop", "Clean boundary management"],
        keyConcepts: ["Sentinel node pattern", "Branch reduction", "Edge case simplification"],
        difficulty: "Easy",
        estimatedMinutes: 15,
        order: 5,
        status: "not_started",
      },
      {
        id: "top-1-6",
        subjectId: "sub-1",
        unitNumber: 2,
        unitTitle: "Unit 2: Linear & Pointer Data Structures",
        topicCode: "2.3",
        title: "Two Pointers: Floyd's Cycle Detection",
        moduleName: "Unit 2: Linear & Pointer Data Structures",
        description: "Fast and slow pointer relative velocity in cyclic loops and finding the cycle entrance node.",
        subtopics: ["Tortoise and hare relative speed (2x)", "Cycle detection proof", "Mathematical derivation of cycle start"],
        keyConcepts: ["Fast & slow pointers", "Cycle detection", "O(1) space invariant"],
        difficulty: "Medium",
        estimatedMinutes: 18,
        order: 6,
        status: "not_started",
      },
      {
        id: "top-1-7",
        subjectId: "sub-1",
        unitNumber: 3,
        unitTitle: "Unit 3: Hierarchical Trees & Search",
        topicCode: "3.1",
        title: "Binary Search Tree Properties & Invariants",
        moduleName: "Unit 3: Hierarchical Trees & Search",
        description: "Left-smaller, right-greater invariant, logarithmic search paths, and BST insertion rules.",
        subtopics: ["BST invariant definition", "Recursive search path", "Insertion without rebalancing"],
        keyConcepts: ["BST property (left < root < right)", "O(h) search complexity"],
        difficulty: "Medium",
        estimatedMinutes: 18,
        order: 7,
        status: "not_started",
      },
      {
        id: "top-1-8",
        subjectId: "sub-1",
        unitNumber: 3,
        unitTitle: "Unit 3: Hierarchical Trees & Search",
        topicCode: "3.2",
        title: "Inorder, Preorder & Postorder Tree Traversals",
        moduleName: "Unit 3: Hierarchical Trees & Search",
        description: "Depth-first recursive visit orders and their applications (sorted output, tree copying, deletion).",
        subtopics: ["Inorder produces monotonic sorted keys", "Preorder serialization", "Postorder bottom-up subtree evaluation"],
        keyConcepts: ["Inorder sorted output", "Call stack recursion", "Subtree evaluation"],
        difficulty: "Medium",
        estimatedMinutes: 18,
        order: 8,
        status: "not_started",
      },
    ],
  },
  {
    id: "sub-2",
    name: "Neuroscience: Memory & Learning",
    description: "Biochemical and cognitive mechanisms of memory consolidation and rapid skill acquisition.",
    targetDate: target2,
    color: "from-emerald-600 to-teal-600",
    icon: "brain",
    resourceNames: ["Cognitive_Psychology_Reading.pdf"],
    webLinks: ["https://nature.com/articles/neuroscience-learning"],
    createdAt: yesterday,
    topics: [
      {
        id: "top-2-1",
        subjectId: "sub-2",
        unitNumber: 1,
        unitTitle: "Unit 1: Memory Decay & Spaced Repetition",
        topicCode: "1.1",
        title: "Ebbinghaus Forgetting Curve & Decay Formula",
        moduleName: "Unit 1: Memory Decay & Spaced Repetition",
        description: "Mathematical decline of retention over time and resetting memory strength via spaced repetitions.",
        subtopics: ["Retention decay formula R = e^(-t/S)", "Initial 48-hour steep drop-off", "Repetition slope flattening"],
        keyConcepts: ["Exponential decay curve", "Memory stability S", "Slope flattening"],
        difficulty: "Easy",
        estimatedMinutes: 16,
        order: 1,
        status: "completed",
        quizScore: 90,
        completedAt: yesterday,
        notes: "Hermann Ebbinghaus discovered that memories fade rapidly within 48 hours unless reinforced. Every review flattens the forgetting slope!",
      },
      {
        id: "top-2-2",
        subjectId: "sub-2",
        unitNumber: 1,
        unitTitle: "Unit 1: Memory Decay & Spaced Repetition",
        topicCode: "1.2",
        title: "Active Recall Testing vs Passive Review",
        moduleName: "Unit 1: Memory Decay & Spaced Repetition",
        description: "The cognitive testing effect: why self-retrieval builds robust neural pathways compared to re-reading.",
        subtopics: ["The testing effect empirical trials", "Desirable difficulties in retrieval", "Fluency illusion in re-reading"],
        keyConcepts: ["Testing effect", "Retrieval effort", "Fluency illusion"],
        difficulty: "Easy",
        estimatedMinutes: 15,
        order: 2,
        status: "not_started",
      },
      {
        id: "top-2-3",
        subjectId: "sub-2",
        unitNumber: 1,
        unitTitle: "Unit 1: Memory Decay & Spaced Repetition",
        topicCode: "1.3",
        title: "Optimal Spacing Intervals (+1, +3, +7, +14, +30d)",
        moduleName: "Unit 1: Memory Decay & Spaced Repetition",
        description: "Expanding interval schedules that maximize consolidation right before memory drops below threshold.",
        subtopics: ["Interval doubling theory", "Long-term maintenance schedules", "Ebbinghaus ladder benchmarks"],
        keyConcepts: ["Expanding intervals", "Threshold retrieval timing"],
        difficulty: "Easy",
        estimatedMinutes: 16,
        order: 3,
        status: "not_started",
      },
      {
        id: "top-2-4",
        subjectId: "sub-2",
        unitNumber: 2,
        unitTitle: "Unit 2: Cellular & Synaptic Mechanisms",
        topicCode: "2.1",
        title: "Hebbian Synapse Plasticity Principle",
        moduleName: "Unit 2: Cellular & Synaptic Mechanisms",
        description: "Hebbian learning rule ('neurons that fire together wire together') and synaptic sensitivity.",
        subtopics: ["Donald Hebb's postulate", "Synchronous pre/post firing", "Structural synapse enlargement"],
        keyConcepts: ["Hebbian wiring", "Synaptic efficacy", "Coincidence detection"],
        difficulty: "Medium",
        estimatedMinutes: 16,
        order: 4,
        status: "not_started",
      },
      {
        id: "top-2-5",
        subjectId: "sub-2",
        unitNumber: 2,
        unitTitle: "Unit 2: Cellular & Synaptic Mechanisms",
        topicCode: "2.2",
        title: "NMDA Receptors & Calcium Influx in LTP",
        moduleName: "Unit 2: Cellular & Synaptic Mechanisms",
        description: "Biochemical trigger of Long-Term Potentiation: magnesium unblocking and calcium signal cascades.",
        subtopics: ["AMPA receptor depolarization", "Magnesium ion expulsion", "CaMKII enzyme activation"],
        keyConcepts: ["NMDA voltage dependence", "Calcium influx", "LTP initiation"],
        difficulty: "Hard",
        estimatedMinutes: 20,
        order: 5,
        status: "not_started",
      },
      {
        id: "top-2-6",
        subjectId: "sub-2",
        unitNumber: 3,
        unitTitle: "Unit 3: Systems Consolidation & Sleep",
        topicCode: "3.1",
        title: "Working Memory Capacity & Cognitive Chunking",
        moduleName: "Unit 3: Systems Consolidation & Sleep",
        description: "Prefrontal cortex capacity limits (4±1 units) and grouping information into meaningful chunks.",
        subtopics: ["Miller & Cowan working memory limits", "Phonological loop vs visuospatial sketchpad", "Chunking hierarchies"],
        keyConcepts: ["Chunking strategy", "Prefrontal executive control", "Cognitive load limit"],
        difficulty: "Easy",
        estimatedMinutes: 16,
        order: 6,
        status: "not_started",
      },
      {
        id: "top-2-7",
        subjectId: "sub-2",
        unitNumber: 3,
        unitTitle: "Unit 3: Systems Consolidation & Sleep",
        topicCode: "3.2",
        title: "Slow-Wave Sleep Spindles & Neocortical Transfer",
        moduleName: "Unit 3: Systems Consolidation & Sleep",
        description: "Hippocampal sharp-wave ripples during deep sleep transferring temporary memory traces to the cortex.",
        subtopics: ["Hippocampal-neocortical dialogue", "Sharp-wave ripple replays", "System-level permanent consolidation"],
        keyConcepts: ["Sleep memory replay", "Neocortical storage", "Slow-wave consolidation"],
        difficulty: "Medium",
        estimatedMinutes: 18,
        order: 7,
        status: "not_started",
      },
    ],
  },
];

export const initialEbbinghausRevisions: EbbinghausRevisionItem[] = [
  {
    id: "rev-top-2-1-stage1",
    topicId: "top-2-1",
    subjectId: "sub-2",
    topicTitle: "Ebbinghaus Forgetting Curve & Decay Formula",
    subjectName: "Neuroscience: Memory & Learning",
    originalCompletionDate: yesterday,
    scheduledDate: today, // DUE TODAY!
    stageNumber: 1,
    intervalDays: 1,
    status: "pending",
  },
  {
    id: "rev-top-1-1-stage1",
    topicId: "top-1-1",
    subjectId: "sub-1",
    topicTitle: "Big-O & Upper Bound Asymptotics",
    subjectName: "Data Structures & Algorithms",
    originalCompletionDate: yesterday,
    scheduledDate: today, // DUE TODAY!
    stageNumber: 1,
    intervalDays: 1,
    status: "pending",
  },
  {
    id: "rev-top-2-1-stage2",
    topicId: "top-2-1",
    subjectId: "sub-2",
    topicTitle: "Ebbinghaus Forgetting Curve & Decay Formula",
    subjectName: "Neuroscience: Memory & Learning",
    originalCompletionDate: yesterday,
    scheduledDate: addDays(today, 2),
    stageNumber: 2,
    intervalDays: 3,
    status: "pending",
  },
  {
    id: "rev-top-1-1-stage2",
    topicId: "top-1-1",
    subjectId: "sub-1",
    topicTitle: "Big-O & Upper Bound Asymptotics",
    subjectName: "Data Structures & Algorithms",
    originalCompletionDate: yesterday,
    scheduledDate: addDays(today, 2),
    stageNumber: 2,
    intervalDays: 3,
    status: "pending",
  },
];

export const initialBadges: AchievementBadge[] = [
  {
    id: "b-first-step",
    title: "First Step Master",
    description: "Completed your first topic with >= 75% MCQ quiz score.",
    icon: "award",
    category: "mastery",
    unlocked: true,
    unlockedAt: yesterday,
    currentCount: 2,
    targetCount: 1,
  },
  {
    id: "b-streak-3",
    title: "Consistency Champ",
    description: "Maintained a 3-day continuous study habit.",
    icon: "flame",
    category: "consistency",
    unlocked: true,
    unlockedAt: yesterday,
    currentCount: 3,
    targetCount: 3,
  },
  {
    id: "b-ebbinghaus-explorer",
    title: "Spaced Repetition Explorer",
    description: "Completed your first Ebbinghaus memory recall session.",
    icon: "repeat",
    category: "ebbinghaus",
    unlocked: false,
    currentCount: 0,
    targetCount: 1,
  },
  {
    id: "b-quiz-whiz",
    title: "Perfect Recall (100% MCQ)",
    description: "Scored 100% on a topic mastery challenge.",
    icon: "sparkles",
    category: "mastery",
    unlocked: true,
    unlockedAt: yesterday,
    currentCount: 1,
    targetCount: 1,
  },
  {
    id: "b-community-scholar",
    title: "Community Scholar",
    description: "Posted a question or shared study insight in the Community Hub.",
    icon: "users",
    category: "community",
    unlocked: true,
    unlockedAt: yesterday,
    currentCount: 1,
    targetCount: 1,
  },
  {
    id: "b-streak-7",
    title: "Unstoppable Momentum",
    description: "7 consecutive days of effortless small daily growth.",
    icon: "zap",
    category: "consistency",
    unlocked: false,
    currentCount: 3,
    targetCount: 7,
  },
];

export const initialCommunityPosts: CommunityPost[] = [
  {
    id: "post-1",
    author: "Alex Morgan",
    authorAvatar: "AM",
    isCurrentUser: true,
    subjectTag: "Data Structures & Algorithms",
    topicTag: "Two-Pointer Technique",
    type: "insight",
    content: "Quick tip for two-pointer problems: if an array is already sorted, you can almost always replace a nested O(n^2) loop with two pointers starting at ends in O(n) time. Game changer for Three Sum!",
    createdAt: "Today at 08:45 AM",
    likes: 6,
    likedByMe: false,
    replies: [
      {
        id: "rep-1-1",
        author: "Priya Sharma",
        authorAvatar: "PS",
        isCurrentUser: false,
        content: "Totally agreed! Same logic applies to palindrome verification and container with most water.",
        createdAt: "Today at 09:12 AM",
      },
    ],
  },
  {
    id: "post-2",
    author: "Liam Chen",
    authorAvatar: "LC",
    isCurrentUser: false,
    subjectTag: "Neuroscience: Memory & Learning",
    topicTag: "Ebbinghaus Curve",
    type: "doubt",
    content: "When testing yourself on Day 3 of Ebbinghaus revision, is it better to write freehand notes first or immediately do MCQs? What works best for long term retention?",
    createdAt: "Yesterday at 6:30 PM",
    likes: 9,
    likedByMe: true,
    replies: [
      {
        id: "rep-2-1",
        author: "Alex Morgan",
        authorAvatar: "AM",
        isCurrentUser: true,
        content: "Definitely write freehand from memory first! The cognitive effort of retrieving information without cues (Active Recall) triggers way stronger synaptic consolidation than just recognizing answers in MCQs.",
        createdAt: "Yesterday at 7:15 PM",
      },
    ],
  },
  {
    id: "post-3",
    author: "Sophia Patel",
    authorAvatar: "SP",
    isCurrentUser: false,
    subjectTag: "StudySync Tips",
    type: "resource",
    content: "Loving the NotebookLM integration! I copied my StudySync topic dossier into NotebookLM and generated a 10-minute Audio Overview deep-dive podcast that I listened to while walking my dog.",
    createdAt: "2 days ago",
    likes: 14,
    likedByMe: false,
    replies: [],
  },
];

export const initialSchedule = generateSmartStudySchedule(initialSubjects, 0, 0, today);

// Alias exports for uppercase convenience
export const INITIAL_SUBJECTS = initialSubjects;
export const INITIAL_SCHEDULE = initialSchedule;
export const INITIAL_REVISIONS = initialEbbinghausRevisions;
export const INITIAL_PREFERENCES = defaultPreferences;
export const INITIAL_POSTS = initialCommunityPosts;
export const INITIAL_BADGES = initialBadges;
